/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionParameterDefinition } from './actionParameterDefinition';


export interface ActionDefinition { 
    /**
     * Identifier of the action definition — used for example when executing an action
     */
    id: string;
    /**
     * name of the action definition, e.g. \"move\"
     */
    name?: string;
    /**
     * title of the action definition, e.g. \"Move\"
     */
    title?: string;
    /**
     * describes the action definition, e.g. \"This will move the matched item to another space.\"
     */
    description?: string;
    /**
     * QNames of the types this action applies to
     */
    applicableTypes: Array<string>;
    /**
     * whether the basic action definition supports action tracking or not
     */
    trackStatus: boolean;
    parameterDefinitions?: Array<ActionParameterDefinition>;
}

