/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionConstraintData } from './actionConstraintData';


/**
 * Response object holding action parameter constraint name and map of its values-labels. 
 */
export interface ActionConstraint { 
    /**
     * Name of the constraint. 
     */
    constraintName?: string;
    /**
     * A list of constraint possbile values along with additional data (label, isNode flag). Sample object could be: ```JSON \"constraintValues\": [            {               \"value\": \"EQUALS\",               \"label\": \"Equals\"            },            {               \"value\": \"CONTAINS\",               \"label\": \"Contains\"            },            {               \"value\": \"BEGINS\",               \"label\": \"Begins With\"            },            {               \"value\": \"ENDS\",               \"label\": \"Ends With\"            },            {               \"value\": \"GREATER_THAN\",               \"label\": \"Greater Than\"            },            {               \"value\": \"GREATER_THAN_EQUAL\",               \"label\": \"Greater Than Or Equal To\"            },            {               \"value\": \"LESS_THAN\",               \"label\": \"Less Than\"            },            {               \"value\": \"LESS_THAN_EQUAL\",               \"label\": \"Less Than Or Equal To\"            }         ] ``` or ```JSON \"constraintValues\": [                         {                             \"value\": \"fa41fd6e-5640-410f-9f3e-93f268186f69\",                             \"label\": \"Start Pooled Review and Approve Workflow\",                             \"isNode\": true                         }                     ] ``` 
     */
    constraintValues?: Array<ActionConstraintData>;
}

