/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Activities describe any past activity in a site, for example creating an item of content, commenting on a node, liking an item of content. 
 */
export interface Activity { 
    /**
     * The id of the person who performed the activity
     */
    postPersonId: string;
    /**
     * The unique id of the activity
     */
    id: number;
    /**
     * The unique id of the site on which the activity was performed
     */
    siteId?: string;
    /**
     * The date time at which the activity was performed
     */
    postedAt?: string;
    /**
     * The feed on which this activity was posted
     */
    feedPersonId: string;
    /**
     * An object summarizing the activity
     */
    activitySummary?: { [key: string]: string; };
    /**
     * The type of the activity posted
     */
    activityType: string;
}

