/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request object holding archive content related paramteres for given content. 
 */
export interface ArchiveContentRequest { 
    /**
     * Optional map (String-String) of archive request properties for given content. 
     */
    archiveParams?: { [key: string]: string; };
}

