/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Category { 
    /**
     * The identifier for the category.
     */
    id: string;
    /**
     * The name of the category.  This must be unique within the parent category. 
     */
    name: string;
    /**
     * The id of the parent category (or -root- if this is a top level category).
     */
    parentId?: string;
    /**
     * True if the category has at least one child category.
     */
    hasChildren?: boolean;
    /**
     * The number of nodes that are assigned to this category.
     */
    count?: number;
    /**
     * The path to this category.
     */
    path?: string;
}

