/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Company { 
    organization?: string;
    address1?: string;
    address2?: string;
    address3?: string;
    postcode?: string;
    telephone?: string;
    fax?: string;
    email?: string;
}

