/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleConditionDefinition } from './simpleConditionDefinition';


export interface CompositeConditionDefinition { 
    /**
     * Whether to invert the logic for this condition (if true then \"not\" is applied to the whole condition)
     */
    inverted?: boolean;
    /**
     * How to combine the clauses of this condition (\"and\" or \"or\")
     */
    booleanMode?: CompositeConditionDefinition.BooleanModeEnum;
    /**
     * Nested list of composite clauses in this condition
     */
    compositeConditions?: Array<CompositeConditionDefinition>;
    /**
     * Nested list of simple (per field) conditions.
     */
    simpleConditions?: Array<SimpleConditionDefinition>;
}
export namespace CompositeConditionDefinition {
    export type BooleanModeEnum = 'and' | 'or';
    export const BooleanModeEnum = {
        And: 'and' as BooleanModeEnum,
        Or: 'or' as BooleanModeEnum
    };
}


