/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Property } from './property';


export interface Definition { 
    /**
     * List of property definitions effective for this node as the result of combining the type with all aspects.
     */
    properties?: Array<Property>;
}

