/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DirectAccessUrl { 
    /**
     * The direct access URL of a binary content
     */
    contentUrl: string;
    /**
     * Flag to control the download method, **true** for attachment URL, **false** for embedded URL
     */
    attachment?: boolean;
    /**
     * The direct access URL would become invalid when the expiry date is reached
     */
    expiresAt?: string;
}

