/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Download { 
    /**
     * number of files added so far in the zip
     */
    filesAdded?: number;
    /**
     * number of bytes added so far in the zip
     */
    bytesAdded?: number;
    /**
     * the id of the download node
     */
    id?: string;
    /**
     * the total number of files to be added in the zip
     */
    totalFiles?: number;
    /**
     * the total number of bytes to be added in the zip
     */
    totalBytes?: number;
    /**
     * the current status of the download node creation
     */
    status?: Download.StatusEnum;
}
export namespace Download {
    export type StatusEnum = 'PENDING' | 'CANCELLED' | 'IN_PROGRESS' | 'DONE' | 'MAX_CONTENT_SIZE_EXCEEDED';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Cancelled: 'CANCELLED' as StatusEnum,
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Done: 'DONE' as StatusEnum,
        MaxContentSizeExceeded: 'MAX_CONTENT_SIZE_EXCEEDED' as StatusEnum
    };
}


