/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A favorite describes an Alfresco entity that a person has marked as a favorite. The target can be a site, file or folder. 
 */
export interface Favorite { 
    /**
     * The guid of the object that is a favorite.
     */
    targetGuid: string;
    /**
     * The time the object was made a favorite.
     */
    createdAt?: string;
    target: object;
    /**
     * A subset of the target favorite properties, system properties and properties already available in the target are excluded.
     */
    properties?: object;
}

