/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FavoriteEntry } from './favoriteEntry';
import { Pagination } from './pagination';


export interface FavoritePagingList { 
    pagination: Pagination;
    entries: Array<FavoriteEntry>;
}

