/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NodeBodyCreateAssociation } from './nodeBodyCreateAssociation';
import { AssociationBody } from './associationBody';
import { ChildAssociationBody } from './childAssociationBody';
import { Definition } from './definition';
import { PermissionsBody } from './permissionsBody';


export interface NodeBodyCreate { 
    /**
     * The name must not contain spaces or the following special characters: * \" < > \\ / ? : and |. The character . must not be used at the end of the name. 
     */
    name: string;
    nodeType: string;
    aspectNames?: Array<string>;
    properties?: object;
    permissions?: PermissionsBody;
    definition?: Definition;
    relativePath?: string;
    association?: NodeBodyCreateAssociation;
    secondaryChildren?: Array<ChildAssociationBody>;
    targets?: Array<AssociationBody>;
}

