/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NodeBodyLock { 
    timeToExpire?: number;
    type?: NodeBodyLock.TypeEnum;
    lifetime?: NodeBodyLock.LifetimeEnum;
}
export namespace NodeBodyLock {
    export type TypeEnum = 'ALLOW_OWNER_CHANGES' | 'FULL';
    export const TypeEnum = {
        AllowOwnerChanges: 'ALLOW_OWNER_CHANGES' as TypeEnum,
        Full: 'FULL' as TypeEnum
    };
    export type LifetimeEnum = 'PERSISTENT' | 'EPHEMERAL';
    export const LifetimeEnum = {
        Persistent: 'PERSISTENT' as LifetimeEnum,
        Ephemeral: 'EPHEMERAL' as LifetimeEnum
    };
}


