/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionElement { 
    authorityId?: string;
    name?: string;
    accessStatus?: PermissionElement.AccessStatusEnum;
}
export namespace PermissionElement {
    export type AccessStatusEnum = 'ALLOWED' | 'DENIED';
    export const AccessStatusEnum = {
        Allowed: 'ALLOWED' as AccessStatusEnum,
        Denied: 'DENIED' as AccessStatusEnum
    };
}


