/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Company } from './company';


export interface PersonBodyCreate { 
    id: string;
    firstName: string;
    lastName?: string;
    description?: string;
    email: string;
    skypeId?: string;
    googleId?: string;
    instantMessageId?: string;
    jobTitle?: string;
    location?: string;
    company?: Company;
    mobile?: string;
    telephone?: string;
    userStatus?: string;
    enabled?: boolean;
    emailNotificationsEnabled?: boolean;
    password: string;
    aspectNames?: Array<string>;
    properties?: object;
}

