/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetworkQuota } from './networkQuota';


/**
 * A network is the group of users and sites that belong to an organization. Networks are organized by email domain. When a user signs up for an Alfresco account , their email domain becomes their Home Network. 
 */
export interface PersonNetwork { 
    /**
     * This network\'s unique id
     */
    id: string;
    /**
     * Is this the home network?
     */
    homeNetwork?: boolean;
    isEnabled: boolean;
    createdAt?: string;
    paidNetwork?: boolean;
    subscriptionLevel?: PersonNetwork.SubscriptionLevelEnum;
    quotas?: Array<NetworkQuota>;
}
export namespace PersonNetwork {
    export type SubscriptionLevelEnum = 'Free' | 'Standard' | 'Enterprise';
    export const SubscriptionLevelEnum = {
        Free: 'Free' as SubscriptionLevelEnum,
        Standard: 'Standard' as SubscriptionLevelEnum,
        Enterprise: 'Enterprise' as SubscriptionLevelEnum
    };
}


