/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A specific preference. 
 */
export interface Preference { 
    /**
     * The unique id of the preference
     */
    id: string;
    /**
     * The value of the preference. Note that this can be of any JSON type.
     */
    value?: string;
}

