/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Constraint } from './constraint';


export interface Property { 
    id: string;
    /**
     * the human-readable title
     */
    title?: string;
    /**
     * the human-readable description
     */
    description?: string;
    /**
     * the default value
     */
    defaultValue?: string;
    /**
     * the name of the property type (e.g. d:text)
     */
    dataType?: string;
    /**
     * define if the property is multi-valued
     */
    isMultiValued?: boolean;
    /**
     * define if the property is mandatory
     */
    isMandatory?: boolean;
    /**
     * define if the presence of mandatory properties is enforced
     */
    isMandatoryEnforced?: boolean;
    /**
     * define if the property is system maintained
     */
    isProtected?: boolean;
    /**
     * list of constraints defined for the property
     */
    constraints?: Array<Constraint>;
}

