/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RatingBody { 
    /**
     * The rating scheme type. Possible values are likes and fiveStar.
     */
    id: RatingBody.IdEnum;
    /**
     * The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar
     */
    myRating: string;
}
export namespace RatingBody {
    export type IdEnum = 'likes' | 'fiveStar';
    export const IdEnum = {
        Likes: 'likes' as IdEnum,
        FiveStar: 'fiveStar' as IdEnum
    };
}


