/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RatingAggregate } from './ratingAggregate';


/**
 * A person can rate an item of content by liking it. They can also remove their like of an item of content. API methods exist to get a list of ratings and to add a new rating. 
 */
export interface Rating { 
    id: string;
    aggregate: RatingAggregate;
    ratedAt?: string;
    /**
     * The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar.
     */
    myRating?: string;
}

