/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentInfo } from './contentInfo';


export interface Rendition { 
    id?: string;
    content?: ContentInfo;
    status?: Rendition.StatusEnum;
}
export namespace Rendition {
    export type StatusEnum = 'CREATED' | 'NOT_CREATED';
    export const StatusEnum = {
        Created: 'CREATED' as StatusEnum,
        NotCreated: 'NOT_CREATED' as StatusEnum
    };
}


