/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SiteBodyCreate { 
    id?: string;
    title: string;
    description?: string;
    visibility: SiteBodyCreate.VisibilityEnum;
}
export namespace SiteBodyCreate {
    export type VisibilityEnum = 'PUBLIC' | 'PRIVATE' | 'MODERATED';
    export const VisibilityEnum = {
        Public: 'PUBLIC' as VisibilityEnum,
        Private: 'PRIVATE' as VisibilityEnum,
        Moderated: 'MODERATED' as VisibilityEnum
    };
}


