/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteContainerEntry } from './siteContainerEntry';
import { Pagination } from './pagination';


export interface SiteContainerPagingList { 
    pagination: Pagination;
    entries: Array<SiteContainerEntry>;
}

