/**
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Tag { 
    /**
     * The identifier for the tag.
     */
    id: string;
    /**
     * The unique name of the tag.
     */
    tag: string;
    /**
     * The number of nodes that this tag has been applied to.
     */
    count?: number;
}

